apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: new-pipeline
spec:
  params:
    - default: 'https://github.com/wpernath/quarkus-simple.git'
      description: Source to the GIT
      name: git-url
      type: string
    - default: main
      description: revision to be used
      name: git-revision
      type: string
    - name: context-dir
      default: "the-source"
      type: string
      description: Where to checkout the source relative to the workspace
    - name: image-name
      type: string
      description: the name of the target image including registry
      default: quay.io/wpernath/quarkus-simple-wow
    - name: image-username
      type: string
      description: the username you use to access the registry
    - name: image-password
      type: string
      description: The password you use to access the registry
    - name: target-namespace
      description: The name of the namespace to apply the result to
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: revision
          value: $(params.git-revision)
        - name: subdirectory
          value: $(params.context-dir)
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: package
      params:
        - name: GOALS
          value:
            - package
            - '-DskipTests'
        - name: CONTEXT_DIR
          value: "$(params.context-dir)"
      runAfter:
        - git-clone
      taskRef:        
        kind: Task
        name: maven-caching
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings
    - name: build-and-push-image
      params:
        - name: GOALS
          value:
            - package
            - '-DskipTests'
            - '-Dquarkus.container-image.build=true'
            - '-Dquarkus.container-image.push=true'
            - '-Dquarkus.container-image.builder=jib'
            - '-Dquarkus.container-image.image=$(params.image-name)'
            - '-Dquarkus.container-image.username=$(params.image-username)'
            - '-Dquarkus.container-image.password=$(params.image-password)'
        - name: CONTEXT_DIR
          value: "$(params.context-dir)"
      runAfter:
        - package
      taskRef:
        kind: Task
        name: maven-caching
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: maven-settings
          workspace: maven-settings
    - name: apply-kustomize
      params: 
        - name: kustomize-dir
          value: $(params.context-dir)/kustomize_ext/overlays/dev
        - name: target-namespace
          value: $(params.target-namespace)
        - name: image-name
          value: $(params.image-name)
        - name: image-digest-path
          value: $(params.context-dir)/target
      taskRef:        
        kind: Task
        name: kustomize
      runAfter:
        - build-and-push-image
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
      optional: false
    - name: maven-settings
      optional: false
